// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: probe.go
//
// Generated by this command:
//
//	mockgen -copyright_file ../../../hack/mockgen_copyright.txt -destination=mock_probe.go -mock_names=Interface=Mock -package=probe -source=probe.go Interface
//

// Package probe is a generated GoMock package.
package probe

import (
	context "context"
	block "local-csi-driver/internal/pkg/block"
	reflect "reflect"

	logr "github.com/go-logr/logr"
	gomock "go.uber.org/mock/gomock"
)

// Mock is a mock of Interface interface.
type Mock struct {
	ctrl     *gomock.Controller
	recorder *MockMockRecorder
	isgomock struct{}
}

// MockMockRecorder is the mock recorder for Mock.
type MockMockRecorder struct {
	mock *Mock
}

// NewMock creates a new mock instance.
func NewMock(ctrl *gomock.Controller) *Mock {
	mock := &Mock{ctrl: ctrl}
	mock.recorder = &MockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mock) EXPECT() *MockMockRecorder {
	return m.recorder
}

// GetDevices mocks base method.
func (m *Mock) GetDevices(ctx context.Context) (*block.DeviceList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevices", ctx)
	ret0, _ := ret[0].(*block.DeviceList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevices indicates an expected call of GetDevices.
func (mr *MockMockRecorder) GetDevices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevices", reflect.TypeOf((*Mock)(nil).GetDevices), ctx)
}

// ScanDevices mocks base method.
func (m *Mock) ScanDevices(ctx context.Context, log logr.Logger) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScanDevices", ctx, log)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScanDevices indicates an expected call of ScanDevices.
func (mr *MockMockRecorder) ScanDevices(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanDevices", reflect.TypeOf((*Mock)(nil).ScanDevices), ctx, log)
}
