apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-node
  labels:
  {{- if .Values.labelsOverride }}
  {{- toYaml .Values.labelsOverride | nindent 4 }}
  {{- else }}
  {{- include "chart.labels" . | nindent 4 }}
  {{- end }}
  annotations:
  {{- toYaml .Values.daemonset.serviceAccount.annotations | nindent 4 }}
