apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-node
  namespace: {{ .Values.serviceAccount.namespace | default .Release.Namespace }}
  labels:
  {{- if gt (len .Values.serviceAccount.labels) 0 }}
  {{- toYaml .Values.serviceAccount.labels | nindent 4 }}
  {{- else }}
  {{- include "chart.labels" . | nindent 4 }}
  {{- end }}

  {{- if gt (len .Values.serviceAccount.annotations) 0 }}
  annotations:
  {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- else if gt (len .Values.daemonset.serviceAccount.annotations) 0 }}
  annotations:
  {{- toYaml .Values.daemonset.serviceAccount.annotations | nindent 4 }}
  {{- end }}
